#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -q stsi
#PBS -l walltime=340:00:00
#PBS -j oe

echo "Running on node:"
hostname

module load R

#myinput example: /stsi/raqueld/vcf/6800_JHS_all_chr_sampleID_c2.vcf
#myoutput example: /stsi/raqueld/0_check_vcf_build/6800_JHS_all_chr_sampleID_c2.BuildChecked
#How to run Example
#qsub 0_check_vcf_build.job -v myinput=/stsi/raqueld/vcf/6800_JHS_all_chr_sampleID_c2.vcf,myoutput=/stsi/raqueld/0_check_vcf_build/6800_JHS_all_chr_sampleID_c2.BuildChecked,copyoutput=yes,gz=yes -N 0_6800_JHS_all_chr_sampleID_c2

mydirname=$(dirname $myinput)

filename=$(basename $myinput)

echo "Running vcf build check"

#change this path to your own path where check_vcf_build.R is located
check_vcf_build=/gpfs/home/raqueld/check_vcf_build/check_vcf_build.R

if [ ! -f $check_vcf_build ]; then
	echo "check_vcf_build.R not found. Make sure you downloaded check_vcf_build.R and changed the check_vcf_build variable inside this job script, so it matches to the path where your check_vcf_build.R if located."
	exit
fi

#check if output directory exists
myoutdir=$(dirname $myoutput)
if [ ! -d $myoutdir ]; then
	mkdir -p $myoutdir
fi

gzstarttime=$(date +%s)

newname=$filename

if [ "$gz" == "yes" ]; then
	newname=$(echo $filename | sed -e 's/\.gz$//g')	
	echo "Extracting $filename to $newname"
	cd $mydirname
	zcat $filename > $newname
fi
gzendtime=$(date +%s)


vcfstarttime=$(date +%s)

Rscript $check_vcf_build $mydirname/$newname > $myoutput

vcfendtime=$(date +%s)

copystarttime=$(date +%s)

#set this to your own path in the shared storage in case you want to copy the results
if [ "$copyoutput" == "yes" ]; then

	echo "copying results to /mnt/stsi/p1/wellderly/dbGaP/Raquel_WIP/final_pipeline/0_check_vcf_build"
	cp $myoutput /mnt/stsi/p1/wellderly/dbGaP/Raquel_WIP/final_pipeline/0_check_vcf_build/

fi

copyendtime=$(date +%s)

vcfruntime=$((vcfendtime-vcfstarttime))
gzruntime=$((gzendtime-gzstarttime))
copyruntime=$((copyendtime-copystarttime))

echo "vcf check run time: $vcfruntime"
echo "Extract run time: $gzruntime"
echo "Copy run time: $copyruntime"

