#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l mem=32gb
#PBS -q sata 
#PBS -l walltime=540:00:00
#PBS -j oe

date

echo "Running on node:"
hostname
pwd

#myoutdir example:
#/stsi/raqueld/2_GH
#myinput example:
#qsub 4_split_QC2.job -v myinput=/gpfs/home/raqueld/mapping_MESA/mesa_genotypes-black.lifted_NCBI36_to_GRCh37.GH.bed,myoutdir=/stsi/raqueld/N_tests,hwe='',geno=0.1,mind=0.1 -N 4_N_mesa_genotypes-black
#qsub 4_split_QC2.job -v myinput=/stsi/raqueld/3_ancestry/6800_JHS_all_chr_sampleID_c1/6800_JHS_all_chr_sampleID_c1.lifted_hg19_to_GRCh37.GH.ancestry-5.bed,myoutdir=/stsi/raqueld/4_split_QC2,hwe='',geno=0.1,mind=0.1 -N 4_6800_JHS_all_chr_sampleID_c1

module load vcftools
module load samtools
module load plink2

#Missingness per individual --mind N
#Missingness per marker --geno N
#Hardy-Weinberg equilibrium --hwe N

starttime=$(date +%s)

export inprefix=$(basename $myinput | sed -e 's/\.bed$//g')
export indir=$(dirname $myinput)
outsubdir=$(basename $myinput | sed -e 's~\.lifted.*~~g')

if [ ! -d $myoutdir/$outsubdir ]; then
	mkdir -p $myoutdir/$outsubdir
fi

cd $myoutdir/$outsubdir

if [ -z "$hwe" ]; then 
	echo "No HWE filtering applied.";
	export hweflag='' 
else 
	export hweflag=$(echo "--hwe $hwe" | tr -d '\n'); 
fi
if [ -z "$mind" ]; then 
	echo "No missingness per individual filtering applied.";
	export mindflag='' 
else 
	export mindflag=$(echo "--mind $mind" | tr -d '\n'); 
fi
if [ -z "$geno" ]; then 
	echo "No missingness per marker filtering applied.";
	export genoflag='' 
else 
	export genoflag=$(echo "--geno $geno" | tr -d '\n'); 
fi

#export SHELL=$(type -p bash)
PLINK_FUN() {

	if [ "$1" -eq 23 ]; then
		plink --bfile $indir/$inprefix --chr $1,X --make-bed $hweflag $mindflag $genoflag --out $inprefix.chr$1
	else
		plink --bfile $indir/$inprefix --chr $1 --make-bed $hweflag $mindflag $genoflag --out $inprefix.chr$1
	
	fi

}
export -f PLINK_FUN

plinkstarttime=$(date +%s)
	parallel -j 16 PLINK_FUN ::: {1..23}
plinkendtime=$(date +%s)

echo "Ready for next step, results ready for phasing are in $myoutdir/$outsubdir"

endtime=$(date +%s)

plinkruntime=$((plinkendtime-plinkstarttime))
overallruntime=$((endtime-starttime))

echo "plink run time: $plinkruntime"
echo "Overall run time: $overallruntime"
