#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l mem=12gb
#PBS -q sata 
#PBS -l walltime=440:00:00
#PBS -j oe

#example 
#qsub 6_impute.job -v myinput=/stsi/raqueld/5_N_tests/mesa_genotypes-white/mesa_genotypes-white.lifted_NCBI36_to_GRCh37.GH.chr18.phased.vcf.gz,myoutdir=/stsi/raqueld/6_N_tests,reftype=HRC -N 6_mesa_genotypes-white.lifted_NCBI36_to_GRCh37.GH.chr18
# if running this step as stand alone tool, input file must have the suffix .lifted_*.chr*.phased.vcf.gz, otherwise the pipeline wont work, if you use the previous step to generate this input file, then it will work fine.
date

echo "Running on node:"
hostname
pwd
echo "myinput $myinput"

module load vcftools
module load samtools
module load minimac4
imputationSoftware=minimac4


inprefix=$(basename $myinput | sed -e 's/\.phased\.vcf\.gz//g')
indir=$(dirname $myinput)
mychr=$(echo $inprefix | sed -e 's/.*\.chr//g')

echo "Chromosome $mychr"
echo "Input prefix $inprefix"
outsubdir=$(basename $myinput | sed -e 's/\.lifted.*//g')

if [ ! -d $myoutdir/$outsubdir ]; then
        mkdir -p $myoutdir/$outsubdir
fi

cd $myoutdir/$outsubdir


if [ "$reftype" == "HRC" ]; then
        echo "Using HRC reference panel, file: /stsi/raqueld/EGA/HRC.r1-1.EGA.GRCh37.chr$mychr.haplotypes.m3vcf.gz"
        myref=/stsi/raqueld/EGA/HRC.r1-1.EGA.GRCh37.chr$mychr.haplotypes.m3vcf.gz
else
    	echo "Using 1KG reference, file: /gpfs/group/torkamani/shaun/1000G_VCF/ALL.chr$mychr.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
        myref=/gpfs/group/torkamani/shaun/1000G_VCF/ALL.chr$mychr.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
fi

echo "Running Imputation"
$imputationSoftware --refHaps $myref \
         --haps $myinput \
         --prefix imputed_$mychr \
         --ignoreDuplicates \
         --minRatio 0.01 --ChunkLengthMb 30.00 --ChunkOverlapMb 6.00 --cpus 16
